### ISSUE TITLE
The colors of the visualizations are not displayed correctly

### ISSUE THREAD

**Issue by chantal-kelm** [opensearch-project/OpenSearch-Dashboards#5422]
**Describe the bug**

In opensearch 2.10.0 the colors of the visualizations are not displayed correctly.

**To Reproduce**
1. Go to Visualize
2. Create a visualization

**Dashboards Version**

2.10.0

**Screenshots**

<img width="1792" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/99441266/d191723b-a130-450d-a88e-ea70d2b0adda">

![image (7)](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/99441266/e840922d-a352-481f-83e6-44d451df1d90)

**Host/Environment (please complete the following information):**
 - OS: [Macos]
 - Browser and version [Google Chrome version 118.0.5993.117]

**Comment by joshuarrrr** [comment]
Thanks @chantal-kelm I can confirm and reproduce. This affects visualizations with split series > 10 items.

**Comment by sduenas** [comment]
@joshuarrrr I see this issue has been tagged to be fixed on 2.12 but I'm not sure if there's someone working actively on it? Can you confirm it or do you need any help to fix it?

**Comment by evamillan** [comment]
This looks like an issue with how colors are ordered on the OUI color palette when using `direction: both`. For 2 rotations, it looks like this:

![imagen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/26812577/8976fb4c-250d-4850-8cee-bd81586c8c0c)

So this could probably be fixed by ordering the palette  by `middle-out` for 3 or more rotations and removing `direction: both` for 2.

**Comment by joshuarrrr** [comment]
Yeah @evamillan that's right. I have a work-in-progress solution. Let me talk to the rest of the team about timing to see if we can still get this in 2.12.

**Comment by evamillan** [comment]
@joshuarrrr Are you still working on this? The issue is still tagged as v2.12, is it planned for any release?

**Comment by geekygirldawn** [comment]
@krisfreedain This issue is causing us some pain within the CHAOSS project - any chance we could get an update on the status of the issue (and the PR with a potential fix)?

**Comment by sduenas** [comment]
> @krisfreedain This issue is causing us some pain within the CHAOSS project - any chance we could get an update on the status of the issue (and the PR with a potential fix)?

@geekygirldawn @evamillan  already submitted a PR with the fix

**Comment by krisfreedain** [comment]
thanks for letting us know @sduenas - do you have a link to the PR?

@wbeckler @AMoo-Miki - once @sduenas shares the PR, can you let us know when this fix can go in? thank you

**Comment by krisfreedain** [comment]
Tracked it down https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7051

**Comment by sduenas** [comment]
@krisfreedain , yes, it's #7051

**Comment by ashwin-pc** [comment]
Hey @krisfreedain @sduenas, I've reach out to @joshuarrrr and he said he'd take a look since he's quite familiar with this code

**Comment by krisfreedain** [comment]
appreciate that @ashwin-pc

**Comment by ldrolez** [comment]
And it would be nice is the palette was "dark mode aware". In dark mode the colors are very dim and not pleasant to the eye
