### ISSUE TITLE
[BUG] Issues while trying to maximize panels or edit a visualization created with a heat map in OpenSearch Dashboard v2.10.0

### ISSUE THREAD

**Issue by vaishali-kare** [opensearch-project/OpenSearch-Dashboards#5433]
**Describe the bug**
Option panel is hidden on OpenSearch Dashboard when tried to maximize panels or edit a visualization created with a heat map within Dashboard.

**To Reproduce**
1. Create a visualization with a heat map.
2. Create Dashboard
3. Add created visualization to dashboard.
4. Save the Dashboard
5. Try clicking on the three dots located upper right-hand corner. 
6. Options tab is hidden

**Expected behavior**
Users should have the ability to resize panels or customize heat map visualizations within the dashboard.
**OpenSearch Version**
v 2.10.0

**Dashboards Version**
v 2.10.0

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/149795651/58ff9cd4-ea47-42ac-bd8a-e1fe68636bde)

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Browser and version: Microsoft Edge for Business
Version 119.0.2151.44 (Official build) (64-bit)

**Comment by ananzh** [comment]
Hey @vaishali-kare, I have tried your reproduction steps but I don't see any issues. The image looks like a "stuck" to me, like some intermittent connection or disconnect with OpenSearch. I would close this issue for now. If you see the issue persist, pls reopen it and @ me directly. Thx.


https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/ba051069-5196-4e05-b980-c3fb29e7d793

**Comment by ananzh** [comment]
Close this issue.

**Comment by vaishali-kare** [comment]
Hi @ananzh ,Are you using Opensearch v 2.10.0? We are experiencing this issue persistently with this version.

**Comment by kavilla** [comment]
Potentially addressed with:

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5190

@vaishali-kare can you define your setup?

How is OpenSearch Dashboards and OpenSearch hosted? Does the client side access OpenSearch Dashboards directly or is there a proxy layer? Wondering because changes might be getting caught in a cached layer and even though the client side is not cached the files are.

Thank you.

**Comment by vaishali-kare** [comment]
The OpenSearch Dashboards and OpenSearch are hosted on OpenStack environment. The client access's the OpenSearch Dashboards directly, there are no layer or caching in between.

**Comment by kavilla** [comment]
@vaishali-kare, just clarify. There is no caching within your OpenStack environment? For the discovery start up process there is caching mechanism on how the bundles are hosted on the server that needs hard reload if the build number hasn't changed.

If you navigate to advanced settings and toggle off `visualization:enablePluginAugmentation` are you still experiencing issues?

Will cc: @ohltyler as the menu is was updated to support vis augmenter.

**Comment by vaishali-kare** [comment]
Even after toggling off visualization:enablePluginAugmentation the issue persists.

**Comment by joshuarrrr** [comment]
Yeah, I can confirm this bug and that disabling `visualization:enablePluginAugmentation` isn't sufficient to resolve, because the check for that setting occurs after the code that causes the error. Note that this bug is only known to affect users using Cognito, because of the way it transforms requests. It should be fixed via #5190, which shipped in the 2.11 release.

**Comment by vaishali-kare** [comment]
Thanks for confirming. We will plan upgrade of Opensearch version based on our roadmap and recheck it.

**Comment by vaishali-kare** [comment]
With 2.14 version of Opensearch issue is resolved.
