### ISSUE TITLE
[ACTION NEEDED] Fix flaky integration tests at distribution level

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/OpenSearch-Dashboards#6337]
**What is the bug?**
It was observed in 2.13.0 and previous other releases that this component manually signed off on the release for failing integration tests. See https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2026486279
The flakiness of the test runs take a lot of time from the release team to collect go/no-go decision and significantly lower the confidence in the release bundles.

**How can one reproduce the bug?**
1. Run integration testing for altering and see the failures. 
2. Issues can be reproduced using the steps declared in AUTOCUT issues for failed integration testing

**What is the expected behavior?**
Tests should be consistently passing.

**Do you have any additional context?**
Please note that this is a hard blocker for 2.14.0 release as per the discussion [here](https://github.com/opensearch-project/opensearch-build/issues/4588)

**Comment by ashwin-pc** [comment]
Flakey test from 2.13: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6373

**Comment by bbarani** [comment]
@ashwin-pc @AMoo-Miki Can you please provide your inputs?

**Comment by ashwin-pc** [comment]
Both the tests should already be resolved. Will let @kavilla reply once he verifies it

**Comment by kavilla** [comment]
Checked previously and passing will make check when RC is ran.

**Comment by gaiksaya** [comment]
Re-tagging the issue with upcoming 2.19 release. Please close if the issue is resolved. Thanks!

**Comment by gaiksaya** [comment]
I think we are still seeing flaky tests for ci-group 2 and ci-group 6
Adding few release managers that can add more. @rishabh6788 @peterzhuamazon

**Comment by ashwin-pc** [comment]
Can you link to the specific test failures? We are also tracking CI group failures across OSD core. I want to see if there is an overlap

**Comment by gaiksaya** [comment]
See the dashboard [here](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',filters:!(('$state':(store:appState),meta:(alias:!n,controlledBy:'1721852613904',disabled:!f,index:'16f55f10-4977-11ef-8565-15a1562cd0a0',key:version,negate:!f,params:(query:'2.19.0'),type:phrase),query:(match_phrase:(version:'2.19.0'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'23eb6520-4977-11ef-bbdd-39a9b324a5aa',key:component,negate:!f,params:(query:OpenSearch-Dashboards-ci-group-6),type:phrase),query:(match_phrase:(component:OpenSearch-Dashboards-ci-group-6)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) for all the tests data. I tried filtering it for 2.19.0 ci-group-6 

For 3.0.0-alpha1, @peterzhuamazon is yet to run the tests I believe. Informed it offline. He will update once those results are in.

**Comment by peterzhuamazon** [comment]
> See the dashboard [here](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',filters:!(('$state':(store:appState),meta:(alias:!n,controlledBy:'1721852613904',disabled:!f,index:'16f55f10-4977-11ef-8565-15a1562cd0a0',key:version,negate:!f,params:(query:'2.19.0'),type:phrase),query:(match_phrase:(version:'2.19.0'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'23eb6520-4977-11ef-bbdd-39a9b324a5aa',key:component,negate:!f,params:(query:OpenSearch-Dashboards-ci-group-6),type:phrase),query:(match_phrase:(component:OpenSearch-Dashboards-ci-group-6)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) for all the tests data. I tried filtering it for 2.19.0 ci-group-6
> 
> For 3.0.0-alpha1, [@peterzhuamazon](https://github.com/peterzhuamazon) is yet to run the tests I believe. Informed it offline. He will update once those results are in.

Just an update, 3.0.0 is still pending a fix for https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1185 so we are not able to run any OSD tests.

We are working closely with the plugin owner of SA Dash to fix that.

Thanks.

**Comment by ashwin-pc** [comment]
@gaiksaya based on the dashboard you shared, Ci group 6 has been stable for a few weeks now. Anything im missing?

<img width="1804" alt="Image" src="https://github.com/user-attachments/assets/715fb3e1-d0a2-4c15-90dc-b330fe3c0519" />

**Comment by gaiksaya** [comment]
We did not run 2.19.0 tests after it was released. Last run was on Feb 10, 2025
You can change the version filter and see for [2.19.1](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'23eb6520-4977-11ef-bbdd-39a9b324a5aa',key:component,negate:!f,params:(query:OpenSearch-Dashboards-ci-group-6),type:phrase),query:(match_phrase:(component:OpenSearch-Dashboards-ci-group-6))),('$state':(store:appState),meta:(alias:!n,controlledBy:'1721852613904',disabled:!f,index:'16f55f10-4977-11ef-8565-15a1562cd0a0',key:version,negate:!f,params:(query:'2.19.1'),type:phrase),query:(match_phrase:(version:'2.19.1')))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)).

[Here](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/21aad140-49f6-11ef-bbdd-39a9b324a5aa?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'23eb6520-4977-11ef-bbdd-39a9b324a5aa',key:component,negate:!f,params:(query:OpenSearch-Dashboards-ci-group-6),type:phrase),query:(match_phrase:(component:OpenSearch-Dashboards-ci-group-6))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'16f55f10-4977-11ef-8565-15a1562cd0a0',key:version,negate:!f,params:(query:'3.0.0-alpha1'),type:phrase),query:(match_phrase:(version:'3.0.0-alpha1')))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Release%20Build%20and%20Integration%20Test%20Results',viewMode:view)) is similar one for current release `3.0.0-alpha1` I believe we are yet to run OSD tests due to SA blocker: https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1185

**Comment by peterzhuamazon** [comment]
3.0.0-alpha1 example:
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/7080/pipeline/157
